export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  segments: TranscriptSegment[];
  language: string;
  isAutoGenerated: boolean;
}

// 유튜브 URL에서 video ID 추출
export function extractVideoId(url: string): string | null {
  const patterns = [
    /[?&]v=([^&#]+)/,
    /youtu\.be\/([^?&#]+)/,
    /youtube\.com\/embed\/([^?&#]+)/,
    /youtube\.com\/shorts\/([^?&#]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

// Innertube API를 통한 자막 추출
export async function fetchTranscript(videoId: string): Promise<TranscriptResult | null> {
  try {
    // 1단계: 영상 페이지에서 ytInitialPlayerResponse 가져오기
    const pageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'Accept-Language': 'ko-KR,ko;q=0.9,en;q=0.8',
      },
    });

    if (!pageResponse.ok) return null;

    const pageHtml = await pageResponse.text();

    // ytInitialPlayerResponse에서 자막 트랙 URL 추출
    const playerResponseMatch = pageHtml.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/);
    if (!playerResponseMatch) return null;

    const playerResponse = JSON.parse(playerResponseMatch[1]) as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            baseUrl: string;
            languageCode: string;
            kind?: string;
            name?: { simpleText?: string };
          }>;
        };
      };
    };

    const captionTracks =
      playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

    if (!captionTracks || captionTracks.length === 0) return null;

    // 언어 우선순위: 한국어 > 영어 > 자동생성 한국어 > 자동생성 영어 > 첫 번째
    const preferred = findPreferredTrack(captionTracks);
    if (!preferred) return null;

    // 2단계: 자막 XML 가져오기
    const captionUrl = preferred.baseUrl + '&fmt=json3';
    const captionResponse = await fetch(captionUrl);
    if (!captionResponse.ok) return null;

    const captionData = await captionResponse.json() as {
      events?: Array<{
        tStartMs?: number;
        dDurationMs?: number;
        segs?: Array<{ utf8?: string }>;
      }>;
    };

    const segments: TranscriptSegment[] = (captionData.events ?? [])
      .filter((event) => event.segs && event.tStartMs !== undefined)
      .map((event) => ({
        text: (event.segs ?? [])
          .map((seg) => seg.utf8 ?? '')
          .join('')
          .replace(/\n/g, ' ')
          .trim(),
        start: (event.tStartMs ?? 0) / 1000,
        duration: (event.dDurationMs ?? 0) / 1000,
      }))
      .filter((seg) => seg.text.length > 0);

    return {
      segments,
      language: preferred.languageCode,
      isAutoGenerated: preferred.kind === 'asr',
    };
  } catch {
    return null;
  }
}

function findPreferredTrack(
  tracks: Array<{
    baseUrl: string;
    languageCode: string;
    kind?: string;
  }>
) {
  const priority = [
    (t: typeof tracks[0]) => t.languageCode === 'ko' && t.kind !== 'asr',
    (t: typeof tracks[0]) => t.languageCode.startsWith('en') && t.kind !== 'asr',
    (t: typeof tracks[0]) => t.languageCode === 'ko',
    (t: typeof tracks[0]) => t.languageCode.startsWith('en'),
    () => true,
  ];

  for (const check of priority) {
    const found = tracks.find(check);
    if (found) return found;
  }
  return null;
}

// 자막 세그먼트를 타임스탬프 포함 텍스트로 변환
export function segmentsToText(segments: TranscriptSegment[]): string {
  return segments
    .map((seg) => {
      const minutes = Math.floor(seg.start / 60);
      const seconds = Math.floor(seg.start % 60);
      const timestamp = `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
      return `[${timestamp}] ${seg.text}`;
    })
    .join('\n');
}
